version: '3.9'

services:
  mysql:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./DbSave:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge